name: Build and deploy AI Chat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  server_build:
    name: Server build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: mv -f server/* .

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Zip artifact for deployment
      run: zip release-server.zip ./* -r

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          release-server.zip
          !venv/

  server_deploy:
    name: Server deploy

    runs-on: ubuntu-latest
    needs: server_build
  
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release-server.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ai-chat-ch'
          slot-name: 'Production'   

  client:
    name: Client build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_DUNE_00354EC03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./client"
          api_location: ""
          output_location: ""
          api_build_command: 'npm run build'
        env: 
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}         

            